version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3001:3000"  # Map container port 3000 to host port 3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=my_db_user
      - DATABASE_PASSWORD=my_db_password
      - DATABASE_NAME=my_db_name
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: sheetrocket-postgres
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    environment:
      - POSTGRES_USER=my_db_user
      - POSTGRES_PASSWORD=my_db_password
      - POSTGRES_DB=my_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
