version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=my_db_name
      - POSTGRES_PASSWORD=my_db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"  # Map container port 3000 to host port 3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=my_db_user
      - DATABASE_PASSWORD=my_db_password
      - DATABASE_NAME=my_db_name
      - JWT_SECRET_KEY=my_jwt_secret
    depends_on:
      - postgres

volumes:
  postgres:  # Named volume for PostgreSQL persistence
